install: gradle build jacocoTestReport sonarqube
language: java
before_install:
  - chmod +x gradlew
addons:
  sonarcloud:
    organization: "tobiaslory" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
# - sonar-scanner